# Generated by Django 4.2 on 2023-05-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ans_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='ans_2',
            field=models.CharField(max_length=255),
        ),
    ]
