# Generated by Django 4.2 on 2023-05-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ans_choices',
            field=models.CharField(choices=[('A', 'Follow up'), ('B', 'Watting'), ('C', 'canceled')], default=0, max_length=1),
        ),
    ]
