# Generated by Django 4.2.1 on 2023-05-19 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0008_confirmeduserprofile_ans_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmeduserprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ans_1',
            field=models.TextField(max_length=1055),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ans_2',
            field=models.TextField(max_length=1055),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
