# Generated by Django 4.2.1 on 2023-05-21 10:43

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_alter_confirmeduserprofile_ans_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ans_question',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Follow up', 'Follow up'), ('Hold up', 'Hold up'), ('Canceled', 'Canceled')], default='nothing', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
