# Generated by Django 4.2.1 on 2023-05-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0011_userprofile_ans_question_userprofile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ans_question',
            field=models.CharField(max_length=255),
        ),
    ]
