# Generated by Django 4.2.1 on 2023-05-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0013_remove_userprofile_ans_question_userprofile_ans_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ans_1',
            field=models.TextField(max_length=1055, null='True'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ans_2',
            field=models.TextField(max_length=1055, null='True'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ans_3',
            field=models.TextField(max_length=1055, null='True'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ans_4',
            field=models.TextField(max_length=1055, null='True'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ans_5',
            field=models.TextField(max_length=1055, null='True'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ans_6',
            field=models.TextField(max_length=1055, null='True'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ans_7',
            field=models.TextField(max_length=1055, null='True'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ans_8',
            field=models.TextField(max_length=1055, null='True'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ans_9',
            field=models.TextField(max_length=1055, null='True'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='business_name',
            field=models.CharField(max_length=70, null='True'),
        ),
    ]
