# Generated by Django 4.2.1 on 2023-05-21 16:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0015_confirmeduserprofile_ans_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmeduserprofile',
            name='ans_question1',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Home', 'Home'), ('About us', 'About us'), ('Products', 'Products'), ('Services', 'Services'), ('Contact us', 'Contact us')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='confirmeduserprofile',
            name='ans_question2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('increase online sales', 'increase online sales'), ('promote brand awareness', 'promote brand awareness'), ('provide information', 'provide information'), ('generate leads', 'generate leads')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ans_question1',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Home', 'Home'), ('About us', 'About us'), ('Products', 'Products'), ('Services', 'Services'), ('Contact us', 'Contact us')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ans_question2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('increase online sales', 'increase online sales'), ('promote brand awareness', 'promote brand awareness'), ('provide information', 'provide information'), ('generate leads', 'generate leads')], max_length=255, null=True),
        ),
    ]
