# Generated by Django 4.2.1 on 2023-05-28 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0016_alter_confirmeduserprofile_ans_question1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmeduserprofile',
            name='current_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
